project:
  type: website

website:
  body-header: | 
    **Download my CV** [**here**](/cv/cv.pdf "download" ){target="_blank"}
  back-to-top-navigation: true
  page-footer: 
    left: "Copyright 2025, Aleksandr Michuda" 
    right:
      - icon: twitter
        href: https://twitter.com/econaleks
      - icon: github
        href: https://github.com/amichuda
      - icon: linkedin
        href: https://www.linkedin.com/in/aleksandr-michuda-3a839b149/
      - icon: envelope
        href: mailto:amichud1@swarthmore.edu
  google-analytics: "G-5860F6QGKQ"
  title: "Aleksandr Michuda"
  navbar:
    background: primary
    search: true
    right:
      - text: CV
        file: cv/cv.qmd
      - text: Transparency and Reproducibility
        file: trans_rep.qmd
      - text: Teaching
        file: teaching/teaching.qmd
      - text: Software
        file: software.qmd

format:
  html: 
    theme: yeti
    toc: true

filters:
  - multibib

bibliography_published: bib/references_published.bib
bibliography_working: bib/references_working.bib
bibliography_other: bib/references_other.bib



